### ISSUE TITLE
add example/demo

### ISSUE THREAD

**Issue by fiws** [sebastianwachter/ScratchCard#1]

**Comment by sebastianwachter** [comment]
The entire project is a example. You may use the provided JavaScript file in your own project. All you need is to set a <canvas> in your html give it a width and a height and set it's id to "myCanvas".

I might actually write a documentation in the near future.

**Comment by fiws** [comment]
gh-pages demo then, maybe?

**Comment by sebastianwachter** [comment]
done http://sebastianwachter.github.io/ScratchCard/
